// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using cpcApi.Data;

#nullable disable

namespace cpcApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260129145059_alter_table_proses_add_kdcabang")]
    partial class alter_table_proses_add_kdcabang
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("cpcApi.Model.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Access")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Keterangan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Photo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("cpcApi.Model.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Cabang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Photo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("cpcApi.Model.Cpc.OrderPengisianKaset", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Jumlah")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("KDBANK")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("KDCABANG")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Lokasi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("MerekMesin")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NomorMesin")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("TanggalOrder")
                        .HasColumnType("datetime2");

                    b.Property<string>("created")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("createdat")
                        .HasColumnType("datetime2");

                    b.Property<string>("updated")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("updatedat")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("OrderPengisianKaset");
                });

            modelBuilder.Entity("cpcApi.Model.Cpc.OrderPengisianKasetDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Denom")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Kaset")
                        .HasColumnType("int");

                    b.Property<string>("KodeKaset")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Lembar")
                        .HasColumnType("int");

                    b.Property<string>("NoSeal")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("KodeKaset");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderPengisianKasetDetail");
                });

            modelBuilder.Entity("cpcApi.Model.Cpc.PengembalianKaset", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Catatan")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DiterimaOleh")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Jumlah")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("KDBANK")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("KDCABANG")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Lokasi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("MerekMesin")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NomorMesin")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("OrderPengisianId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("TanggalTerima")
                        .HasColumnType("datetime2");

                    b.Property<string>("created")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("createdat")
                        .HasColumnType("datetime2");

                    b.Property<string>("updated")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("updatedat")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("PengembalianKaset");
                });

            modelBuilder.Entity("cpcApi.Model.Cpc.PengembalianKasetDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Denom")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Kaset")
                        .HasColumnType("int");

                    b.Property<string>("KasetStockIdKaset")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("KodeKaset")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Lembar")
                        .HasColumnType("int");

                    b.Property<string>("NoSeal")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PengembalianId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("KasetStockIdKaset");

                    b.HasIndex("PengembalianId");

                    b.ToTable("PengembalianKasetDetail");
                });

            modelBuilder.Entity("cpcApi.Model.Cpc.ProsesKotakUangCpc", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("JenisUang")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("JumlahLembar")
                        .HasColumnType("int");

                    b.Property<string>("NomorKotakUang")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NomorSeal")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("ProsesSetPersiapanUangCpcId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("UrutanKolom")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProsesSetPersiapanUangCpcId", "UrutanKolom")
                        .IsUnique()
                        .HasDatabaseName("UX_KOTAK_CPC_SET_URUTAN");

                    b.ToTable("ProsesKotakUangCpc", (string)null);
                });

            modelBuilder.Entity("cpcApi.Model.Cpc.ProsesPersiapanUangCpc", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("JabatanPetugas")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<TimeOnly>("JamMulai")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("JamSelesai")
                        .HasColumnType("time");

                    b.Property<int>("JenisProses")
                        .HasColumnType("int");

                    b.Property<string>("KdCabang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KodeBank")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Meja")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("NamaPetugas")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NomorDvr")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PathTtdPetugas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("TanggalDibuat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TanggalFinal")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("TanggalProses")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_PROSES_CPC_STATUS");

                    b.HasIndex("KodeBank", "TanggalProses")
                        .HasDatabaseName("IX_PROSES_CPC_BANK_TANGGAL");

                    b.ToTable("ProsesPersiapanUangCpc", (string)null);
                });

            modelBuilder.Entity("cpcApi.Model.Cpc.ProsesSetPersiapanUangCpc", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProsesPersiapanUangCpcId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SetKe")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProsesPersiapanUangCpcId", "SetKe")
                        .IsUnique()
                        .HasDatabaseName("UX_SET_CPC_PROSES_SETKE");

                    b.ToTable("ProsesSetPersiapanUangCpc", (string)null);
                });

            modelBuilder.Entity("cpcApi.Model.MasterData.KasetMovement", b =>
                {
                    b.Property<long>("IdMovement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdMovement"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("FromLocation")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IdKaset")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NoWO")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ToLocation")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Wsid")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("created")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("createdat")
                        .HasColumnType("datetime2");

                    b.Property<string>("updated")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("updatedat")
                        .HasColumnType("datetime2");

                    b.HasKey("IdMovement");

                    b.HasIndex("NoWO")
                        .HasDatabaseName("IX_KASET_MOVEMENT_NOWO");

                    b.HasIndex("Wsid")
                        .HasDatabaseName("IX_KASET_MOVEMENT_WSID");

                    b.HasIndex("IdKaset", "created")
                        .HasDatabaseName("IX_KASET_MOVEMENT_KASET_DATE");

                    b.ToTable("KasetMovement");
                });

            modelBuilder.Entity("cpcApi.Model.MasterData.KasetStock", b =>
                {
                    b.Property<string>("IdKaset")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LocationId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LocationType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("IdKaset");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_KASET_STOCK_STATUS");

                    b.HasIndex("LocationType", "LocationId")
                        .HasDatabaseName("IX_KASET_STOCK_LOCATION");

                    b.HasIndex("Status", "LocationType")
                        .HasDatabaseName("IX_KASET_STOCK_READY");

                    b.ToTable("KasetStock");
                });

            modelBuilder.Entity("cpcApi.Model.MasterData.MasterKaset", b =>
                {
                    b.Property<string>("IdKaset")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Jenis")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("KdBank")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("KdCabang")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("KdKasetBank")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("KdMerek")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("NmBank")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NoSerial")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StatusFisik")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Tipe")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("created")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("createdat")
                        .HasColumnType("datetime2");

                    b.Property<string>("updated")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("updatedat")
                        .HasColumnType("datetime2");

                    b.HasKey("IdKaset");

                    b.HasIndex("KdBank")
                        .HasDatabaseName("IX_MST_KASET_KDBANK");

                    b.HasIndex("KdMerek")
                        .HasDatabaseName("IX_MST_KASET_KDMEREK");

                    b.HasIndex("NoSerial")
                        .IsUnique()
                        .HasDatabaseName("UQ_MST_KASET_NOSERIAL");

                    b.HasIndex("StatusFisik")
                        .HasDatabaseName("IX_MST_KASET_STATUSFISIK");

                    b.HasIndex("KdCabang", "StatusFisik")
                        .HasDatabaseName("IX_MST_KASET_CABANG_STATUS");

                    b.ToTable("MasterKaset");
                });

            modelBuilder.Entity("cpcApi.Model.MasterData.MasterMerekKaset", b =>
                {
                    b.Property<string>("KdMerek")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<string>("Keterangan")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NmMerek")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("created")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("createdat")
                        .HasColumnType("datetime2");

                    b.Property<string>("updated")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("updatedat")
                        .HasColumnType("datetime2");

                    b.HasKey("KdMerek");

                    b.HasIndex("NmMerek")
                        .IsUnique()
                        .HasDatabaseName("UQ_MST_MEREK_KASET_NAMA");

                    b.ToTable("MasterMerekKaset");
                });

            modelBuilder.Entity("cpcApi.Model.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiredAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RefreshToken");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("cpcApi.Model.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("cpcApi.Model.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("cpcApi.Model.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("cpcApi.Model.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("cpcApi.Model.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("cpcApi.Model.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("cpcApi.Model.Cpc.OrderPengisianKasetDetail", b =>
                {
                    b.HasOne("cpcApi.Model.MasterData.KasetStock", "KasetStock")
                        .WithMany("OrderDetails")
                        .HasForeignKey("KodeKaset")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("cpcApi.Model.Cpc.OrderPengisianKaset", "Order")
                        .WithMany("Details")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KasetStock");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("cpcApi.Model.Cpc.PengembalianKasetDetail", b =>
                {
                    b.HasOne("cpcApi.Model.MasterData.KasetStock", "KasetStock")
                        .WithMany()
                        .HasForeignKey("KasetStockIdKaset");

                    b.HasOne("cpcApi.Model.Cpc.PengembalianKaset", "Pengembalian")
                        .WithMany("Details")
                        .HasForeignKey("PengembalianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KasetStock");

                    b.Navigation("Pengembalian");
                });

            modelBuilder.Entity("cpcApi.Model.Cpc.ProsesKotakUangCpc", b =>
                {
                    b.HasOne("cpcApi.Model.Cpc.ProsesSetPersiapanUangCpc", "Set")
                        .WithMany("DaftarKotakUang")
                        .HasForeignKey("ProsesSetPersiapanUangCpcId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Set");
                });

            modelBuilder.Entity("cpcApi.Model.Cpc.ProsesSetPersiapanUangCpc", b =>
                {
                    b.HasOne("cpcApi.Model.Cpc.ProsesPersiapanUangCpc", "Proses")
                        .WithMany("DaftarSet")
                        .HasForeignKey("ProsesPersiapanUangCpcId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proses");
                });

            modelBuilder.Entity("cpcApi.Model.MasterData.KasetMovement", b =>
                {
                    b.HasOne("cpcApi.Model.MasterData.MasterKaset", "Kaset")
                        .WithMany("Movements")
                        .HasForeignKey("IdKaset")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Kaset");
                });

            modelBuilder.Entity("cpcApi.Model.MasterData.KasetStock", b =>
                {
                    b.HasOne("cpcApi.Model.MasterData.MasterKaset", "Kaset")
                        .WithOne("Stock")
                        .HasForeignKey("cpcApi.Model.MasterData.KasetStock", "IdKaset")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kaset");
                });

            modelBuilder.Entity("cpcApi.Model.MasterData.MasterKaset", b =>
                {
                    b.HasOne("cpcApi.Model.MasterData.MasterMerekKaset", "Merek")
                        .WithMany("Kasets")
                        .HasForeignKey("KdMerek")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Merek");
                });

            modelBuilder.Entity("cpcApi.Model.Cpc.OrderPengisianKaset", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("cpcApi.Model.Cpc.PengembalianKaset", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("cpcApi.Model.Cpc.ProsesPersiapanUangCpc", b =>
                {
                    b.Navigation("DaftarSet");
                });

            modelBuilder.Entity("cpcApi.Model.Cpc.ProsesSetPersiapanUangCpc", b =>
                {
                    b.Navigation("DaftarKotakUang");
                });

            modelBuilder.Entity("cpcApi.Model.MasterData.KasetStock", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("cpcApi.Model.MasterData.MasterKaset", b =>
                {
                    b.Navigation("Movements");

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("cpcApi.Model.MasterData.MasterMerekKaset", b =>
                {
                    b.Navigation("Kasets");
                });
#pragma warning restore 612, 618
        }
    }
}
